### ISSUE TITLE
Loud percussive sound that plays even when phone is muted

### ISSUE THREAD

**Issue by manskou** [manskou/Nerfus-Metera-issues#11]
Possibly an engine bug, happened three times in the same run before and whilst fighting Fitas boss.

**Comment by AngeloGi** [comment]
It's the Boss Incoming SFX lol @ description. @PwnzorBot4000 should fix that.

**Comment by manskou** [comment]
The phone's sound, was MUTED and it wasn't the sound I've heard, it was very short, less than a second.

**Comment by PwnzorBot4000** [comment]
Code seems ok. Is this still valid?

**Comment by manskou** [comment]
was device-specific, possibly Rom-specific, the audio API glitches and ignores audio level (even if muted). Shouldn't bother us
