### ISSUE TITLE
Fitas boss Projectiles are dissapearing after a second or two

### ISSUE THREAD

**Issue by DionisisR** [manskou/Nerfus-Metera-issues#15]
1- Projectiles are dissapearing after a second or two, making the boss miss all the time if the player is on the bottom of the screen

**Comment by PwnzorBot4000** [comment]
Fix uploaded for 0.3.31.

**Comment by PwnzorBot4000** [comment]
Increased Harim's life to allow for feedback, for 0.3.32.
