### ISSUE TITLE
Secondary is very slow, ends up chasing enemies idefinitely

### ISSUE THREAD

**Issue by manskou** [manskou/Nerfus-Metera-issues#2]
if the homing weapon fires while an enemy is close to the player, it can chase after the enemy indefinitely.

## Proposed fix: 
 - Make projectile faster
 - Reduce fire rate

**Comment by AngeloGi** [comment]
Both change by upgrades...

**Comment by manskou** [comment]
of course, the point of an upgrade is to make something better, it has to be worth it in the first place. The user shouldn't invest in so many points just to make it usable...


also possible performance hog if the projectiles don't hit someone?

**Comment by AngeloGi** [comment]
Yeap I'll make it a bit faster and make speed improvements cost more because the weap is too strong if faster. 

Nope, projectiles suicide after 12 seconds of flight time or when no target is around.

**Comment by AngeloGi** [comment]
Fixed.
