### ISSUE TITLE
Colliding on something, immidiately destroys it. you take no dmg

### ISSUE THREAD

**Issue by DionisisR** [manskou/Nerfus-Metera-issues#24]

**Comment by PwnzorBot4000** [comment]
confirmed, damageOnTouch component is missing from many enemies. Note that currently the player deals 10 damage when colliding with something, enemies with damageOnTouch should do likewise.

**Comment by PwnzorBot4000** [comment]
Fix uploaded for 0.3.31.

**Comment by DionisisR** [comment]
Tested on Nornal enemies. Still the same problem

**Comment by PwnzorBot4000** [comment]
Confirmed, DamageOnTouch component was missing from all normals. Fix uploaded for 0.3.32.
