### ISSUE TITLE
When secondary is enabled loud percussive sounds are played randomly

### ISSUE THREAD

**Issue by manskou** [manskou/Nerfus-Metera-issues#3]
These sounds are much louder than any other sfx. I think they are triggered by an enemy exploding but I'm not sure and it doesn't always happen.

The sounds vary in pitch but they're all loud and sound like a snare...

Possibly a sound is triggered multiple times at once and then cutting off? That explains the loudness but not the pitch....

**Comment by AngeloGi** [comment]
A) Android doesn't support pitch variation so they can't have different pitch
B) Cannot reproduce in editor or phone

**Comment by manskou** [comment]
will test with new build and report back
